import{a as q,S as B,i as n}from"./assets/vendor-BAQQTdrx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function f(o,t=1){const a="55631968-7584b9a203dbb647b76045b43",s="https://pixabay.com/api/",e={key:a,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(s,{params:e})).data}const M=new B(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery"),y=document.querySelector(".load-more"),p=document.querySelector(".loader");function $(){g.innerHTML=""}function h(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:v,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${r}</p>
        <p class="info-item"><b>Views</b>${i}</p>
        <p class="info-item"><b>Comments</b>${v}</p>
        <p class="info-item"><b>Downloads</b>${S}</p>
      </div>
    </li>
  `).join("");g.insertAdjacentHTML("beforeend",t),M.refresh()}function b(){p.classList.add("is-visible")}function L(){p.classList.remove("is-visible")}function w(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}let l="",c=1,u=0;const m=document.querySelector(".form"),P=document.querySelector(".load-more");m.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),l===""){n.warning({message:"Please enter a search term"});return}c=1,$(),d(),b();try{const t=await f(l,c);if(u=t.totalHits,t.hits.length===0){n.error({message:"Sorry, no images found. Try again!"});return}h(t.hits),u>15&&w()}catch(t){console.error(t),n.error({message:"Something went wrong!"})}finally{L(),m.reset()}});P.addEventListener("click",async()=>{c+=1,d(),b();try{const o=await f(l,c);h(o.hits),E();const t=Math.ceil(u/15);c>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch{n.error({message:"Error loading more images!"})}finally{L()}});function E(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
