import{a as S,S as M,i as n}from"./assets/vendor-BAQQTdrx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function f(o,t=1){const s="55631968-7584b9a203dbb647b76045b43",a="https://pixabay.com/api/",e={key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(a,{params:e})).data}const q=new M(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery"),y=document.querySelector(".load-more"),p=document.querySelector(".loader");function B(){g.innerHTML=""}function h(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:c,comments:v,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${r}</p>
        <p class="info-item"><b>Views</b>${c}</p>
        <p class="info-item"><b>Comments</b>${v}</p>
        <p class="info-item"><b>Downloads</b>${w}</p>
      </div>
    </li>
  `).join("");g.insertAdjacentHTML("beforeend",t),q.refresh()}function b(){p.classList.add("is-visible")}function L(){p.classList.remove("is-visible")}function u(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}let l="",i=1,m=0;const P=document.querySelector(".form"),$=document.querySelector(".load-more");P.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),l===""){n.warning({message:"Please enter a search term"});return}i=1,B(),d(),b();try{const t=await f(l,i);if(m=t.totalHits,t.hits.length===0){n.error({message:"Sorry, no images found. Try again!"});return}h(t.hits);const s=Math.ceil(m/15);i>=s?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):u()}catch(t){console.error(t),n.error({message:"Something went wrong!"})}finally{L()}});$.addEventListener("click",async()=>{i+=1,d(),b();try{const o=await f(l,i);h(o.hits),E();const t=Math.ceil(m/15);i>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):u()}catch(o){console.error(o),n.error({message:"Error loading more images!"}),u()}finally{L()}});function E(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
