import{a as M,S as P,i as a}from"./assets/vendor-BAQQTdrx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(o,t=1){const s="55631968-7584b9a203dbb647b76045b43",n="https://pixabay.com/api/",e={key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await M.get(n,{params:e})).data}const q=new P(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".gallery"),y=document.querySelector(".load-more"),p=document.querySelector(".loader");function B(){h.innerHTML=""}function b(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:c,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${r}</p>
        <p class="info-item"><b>Views</b>${c}</p>
        <p class="info-item"><b>Comments</b>${w}</p>
        <p class="info-item"><b>Downloads</b>${S}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),q.refresh()}function L(){p.classList.add("is-visible")}function v(){p.classList.remove("is-visible")}function f(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}let d="",i=1,u=0;const m=document.querySelector(".form"),$=document.querySelector(".load-more");m.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.currentTarget.elements["search-text"].value.trim(),d===""){a.warning({message:"Please enter a search term"});return}i=1,B(),l(),L();try{const t=await g(d,i);if(u=t.totalHits,t.hits.length===0){a.error({message:"Sorry, no images found. Try again!"});return}b(t.hits);const s=Math.ceil(u/15);i>=s?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):f()}catch(t){console.error(t),a.error({message:"Something went wrong!"})}finally{v(),m.reset()}});$.addEventListener("click",async()=>{i+=1,l(),L();try{const t=await g(d,i);b(t.hits),E();const s=Math.ceil(u/15);i>=s?(l(),a.info({message:"We're sorry, but you've reached the end of search results."})):f()}catch{a.error({message:"Error loading more images!"})}finally{v()}const o=Math.ceil(u/15);o>0&&i>=o?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):o>1&&f()});function E(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
